### PR TITLE
Fixes 'charging since' text logic.

### PR DESCRIPTION
**Pull request by nata1993**
Fixes the #10 issue I created recently. Not exactly best solution but apparently works. Not using any Fastlane or anything for revision change etc so have to bump versions etc up from your side I guess.

### CODE REVIEW

**Comment by dubrowgn** [comment]
As far as I can tell, this doesn't materially change the logic at all. I would still expect "ChargingSince" to reset if you close and re-open the app (I don't think this is strictly deterministic, since the OS ultimately decides when to actually close the app. Swiping the app away works on my device. Android 13 can also do it through the new tasks UI they added).

**Comment by nata1993** [comment]
Yes, I saw the problem you explained later after the pull request. The state is now persistent until app close which is still improvement compared to each tick update of time since put on charging and now there is something to work with.  My guess is the new variable "state" should be moved to the main activity class instead of creating it inside main activity function since otherwise the variable is recreated with default state each time main activity function is called.

**Comment by nata1993** [comment]
Tested the theory, theory sank to the bottom. Found workaround but now facing nullException on onResume() when opening the app and then on new try its all reset anyway again and the logcat doesnt give enough info for me to figure it out right now. Back to sleep then until some idea pops up.

**Comment by dubrowgn** [comment]
The root issue here is the main activity won't be alive most of the time. When it is not alive, it can't receive plug/unplug events from the OS. https://github.com/dubrowgn/wattz/commit/45e16a460060e183bd1e940eb620a645a53552f9 fixes this by making the long living StatusService own this data instead.

**Pull request closed without merging**
